query BuscaRepositorios($queryString: String!, $qtd: Int!, $cursor: String) {
  search(query: $queryString, type: REPOSITORY, first: $qtd, after: $cursor) {
    repositoryCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ... on Repository {
        nameWithOwner
        stargazerCount
        createdAt
        updatedAt
        pushedAt
        releases {
          totalCount
        }
        primaryLanguage {
          name
        }
        issuesAbertas: issues(states: OPEN) {
          totalCount
        }
        issuesFechadas: issues(states: CLOSED) {
          totalCount
        }
        prsAceitas: pullRequests(states: MERGED) {
          totalCount
        }
      }
    }
  }
}
